sudo: false

language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

env:
  global:
    - HARNESS_OPTIONS=j1:c
    - HARNESS_TIMER=1
    - AUTOMATED_TESTING=1
    - NONINTERACTIVE_TESTING=1
    - PERL_MM_USE_DEFAULT=1
    - RELEASE_TESTING=1
    - EXTENDED_TESTING=1
    - TEST_MYSQL_USER=root
    - TEST_MYSQL_PASS=

before_install:
  - cpanm -nq Devel::Cover::Report::Coveralls
  - cpanm -nq DBD::mysql
  - echo -e "driver_dsn = dbi:mysql:\nusername = root" > ~/.test-database
install:
  - cpanm -nq --installdeps .
script:
  - perl Build.PL && ./Build && cover -test
after_success:
  - cover -report coveralls
